# Generated by Django 2.2.23 on 2021-05-30 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('custom_number', models.IntegerField(verbose_name='Customer Number')),
                ('shirt', models.IntegerField(blank=True, null=True, verbose_name='T-Shirt')),
                ('trouser', models.IntegerField(blank=True, null=True, verbose_name='Trouser/Short')),
                ('underwear', models.IntegerField(blank=True, null=True, verbose_name='Single/Boxers')),
                ('native', models.IntegerField(blank=True, null=True, verbose_name='Complete Native')),
                ('duvet', models.IntegerField(blank=True, null=True, verbose_name='Duvet')),
                ('duver_beddings', models.IntegerField(blank=True, null=True, verbose_name='Duvet and Beddings')),
                ('towel', models.IntegerField(blank=True, null=True, verbose_name='Towel')),
                ('dropp_off', models.DateTimeField(auto_now=True, null=True)),
                ('commission', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refered Byss')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date Of Birth')),
                ('reason_for_registering', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(verbose_name='Registration Date')),
                ('exp_date', models.DateTimeField(verbose_name='Expiring Date')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes')),
                ('refered_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Invalid first name entered', regex="^[A-Za-z]([a-zA-Z ,\\'\\.]*)$")])),
                ('last_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Invalid last name entered', regex='^[a-zA-Z]+$')])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. Only 10 digits allowed.', regex='^\\d{10,10}$')])),
                ('address', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Profile Picture')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('nationality', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=120)),
                ('expired', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='earning.Members')),
            ],
            options={
                'verbose_name': 'Ticket Number ',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earning.Package'),
        ),
    ]
