# Generated by Django 2.2.23 on 2021-06-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='earning.User'),
            preserve_default=False,
        ),
    ]
